#!/bin/bash
#
# Spins up 1-5 docker containers to generate ICE RDF for NCBI taxonomy
# code 9606 (human). The single input parameter should be an integer (1-5)
# indicating the number of docker containers to use.
#
# This script inspired by:
# http://kimh.github.io/blog/en/docker/using-docker-to-run-cucumber-tests-in-parallel/
#

TAX="-t 9606"

case $1 in
    1) DATASOURCES=("SANTOS2016,HGNC,NCBIGENE_GENEINFO,NCBIGENE_REFSEQUNIPROTCOLLAB,GOA_HUMAN,HP_ANNOTATIONS_ALL_SOURCES,IREFWEB_HUMAN_ONLY,REFSEQ_RELEASECATALOG,NCBIGENE_GENE2REFSEQ,UNIPROT_SWISSPROT,UNIPROT_IDMAPPING")
       ;;
    2) DATASOURCES=("SANTOS2016,HGNC,NCBIGENE_GENEINFO,NCBIGENE_REFSEQUNIPROTCOLLAB,GOA_HUMAN,HP_ANNOTATIONS_ALL_SOURCES,IREFWEB_HUMAN_ONLY,REFSEQ_RELEASECATALOG,NCBIGENE_GENE2REFSEQ" "UNIPROT_SWISSPROT,UNIPROT_IDMAPPING")
       ;;
    3) DATASOURCES=("SANTOS2016,HGNC,NCBIGENE_GENEINFO,NCBIGENE_REFSEQUNIPROTCOLLAB,GOA_HUMAN,HP_ANNOTATIONS_ALL_SOURCES,IREFWEB_HUMAN_ONLY,REFSEQ_RELEASECATALOG,NCBIGENE_GENE2REFSEQ" "UNIPROT_SWISSPROT" "UNIPROT_IDMAPPING")
       ;;
    4) DATASOURCES=("SANTOS2016,HGNC,NCBIGENE_GENEINFO,NCBIGENE_REFSEQUNIPROTCOLLAB,GOA_HUMAN,HP_ANNOTATIONS_ALL_SOURCES,IREFWEB_HUMAN_ONLY" "REFSEQ_RELEASECATALOG,NCBIGENE_GENE2REFSEQ" "UNIPROT_SWISSPROT" "UNIPROT_IDMAPPING")
       ;;
    5) DATASOURCES=("SANTOS2016,HGNC,NCBIGENE_GENEINFO,NCBIGENE_REFSEQUNIPROTCOLLAB,GOA_HUMAN,HP_ANNOTATIONS_ALL_SOURCES" "IREFWEB_HUMAN_ONLY" "REFSEQ_RELEASECATALOG,NCBIGENE_GENE2REFSEQ" "UNIPROT_SWISSPROT" "UNIPROT_IDMAPPING")
       ;;
    *) echo "Expected a number between 1-5 for the number of Docker containers to spin up to generate RDF. Observed $1 instead. By default, only a single container will be used for generating RDF."
       DATASOURCES=("SANTOS2016,HGNC,NCBIGENE_GENEINFO,NCBIGENE_REFSEQUNIPROTCOLLAB,GOA_HUMAN,HP_ANNOTATIONS_ALL_SOURCES,IREFWEB_HUMAN_ONLY,REFSEQ_RELEASECATALOG,NCBIGENE_GENE2REFSEQ,UNIPROT_SWISSPROT,UNIPROT_IDMAPPING")
       ;;
esac

DID=""
COUNTER=1
for ds in "${DATASOURCES[@]}"
do
    echo "Starting kabob-base container to process: $ds"
    DID=$DID" "`docker run -d --name "rdf_gen_$COUNTER" --volumes-from kabob_data billbaumgartner/kabob-base:0.1 ./ice-rdf-gen.sh "$TAX" "$ds" "$COUNTER"`
    COUNTER=$((COUNTER + 1))
done
docker wait $DID
docker rm $DID
